BEGIN;

INSERT INTO emergencia (id_emergencia, asunto, descripcion, fecha, activa) VALUES (1, 'vestibulum', 'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum.', '30/9/2008', false);
INSERT INTO emergencia (id_emergencia, asunto, descripcion, fecha, activa) VALUES (2, 'a feugiat', 'Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', '6/5/2009', false);
INSERT INTO emergencia (id_emergencia, asunto, descripcion, fecha, activa) VALUES (3, 'consequat metus', 'Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.', '6/6/2005', false);
INSERT INTO emergencia (id_emergencia, asunto, descripcion, fecha, activa) VALUES (4, 'erat curabitur gravida', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum.', '10/6/2016', true);
INSERT INTO emergencia (id_emergencia, asunto, descripcion, fecha, activa) VALUES (5, 'nibh', 'Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.', '20/10/2002', false);
INSERT INTO emergencia (id_emergencia, asunto, descripcion, fecha, activa) VALUES (6, 'non pretium', 'Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', '5/12/2019', false);
INSERT INTO emergencia (id_emergencia, asunto, descripcion, fecha, activa) VALUES (7, 'magna', 'Nunc purus. Phasellus in felis.', '20/3/2011', false);
INSERT INTO emergencia (id_emergencia, asunto, descripcion, fecha, activa) VALUES (8, 'sed', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit.', '27/2/2003', false);
INSERT INTO emergencia (id_emergencia, asunto, descripcion, fecha, activa) VALUES (9, 'mi in porttitor', 'Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.', '7/8/2006', true);
INSERT INTO emergencia (id_emergencia, asunto, descripcion, fecha, activa) VALUES (10, 'justo', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', '3/8/2006', false);

END;